name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
        
        - name: Synopsys Intelligent Security Scan
  # You may pin to the exact commit or the version.
  # uses: synopsys-sig/intelligent-security-scan@80672d7aaafdedd481e94902dfa26520e1fd967b
  uses: synopsys-sig/intelligent-security-scan@2022.12.0
  with:
    # The server Host URL for Intelligent Scan Engine eg http://localhost:1111 or https://21b7.ngrok.io
    ioServerUrl: # default is http://localhost:9090
    # The server password for Intelligent Scan Engine
    ioServerToken: # optional, default is 
    # HTTP URL to download IO Manifest file synopsys-io.yml
    ioManifestUrl: # optional
    # The server Host URL for Intelligent Scan Workflow Engine eg http://localhost:1111 or https://21b7.ngrok.io
    workflowServerUrl: # default is http://localhost:9091
    # The workflow jar version to retrieve for Intelligent Scan Engine
    workflowVersion: # optional, default is 2022.12.0
    # The run ID from IO stage job
    runId: # optional, default is 
    # Additional arguments required for workflow engine arguments
    additionalWorkflowArgs: 
    # Additional arguments required for workflow engine arguments
    stage: # default is IO
    # Type of Manifest file for IO
    manifestType: # optional, default is yml
